// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi0Qdv9wAZ9MaPoKgJPZ5myyfIbhwm5Dg',
    appId: '1:554357086924:android:0c5832cb05f79f56a08069',
    messagingSenderId: '554357086924',
    projectId: 'rblmalaysia',
    storageBucket: 'rblmalaysia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAylWmJjfPqD1Nm6dE4biv9VhrIFnGNEY0',
    appId: '1:554357086924:ios:e63b5d9a7895bb60a08069',
    messagingSenderId: '554357086924',
    projectId: 'rblmalaysia',
    storageBucket: 'rblmalaysia.firebasestorage.app',
    androidClientId: '554357086924-cscr7hqg4r7c1otqp7oq8v4ththmg3mp.apps.googleusercontent.com',
    iosClientId: '554357086924-j1m2h0b50437orha69ps0aj81efld8ue.apps.googleusercontent.com',
    iosBundleId: 'com.example.rblAdmin',
  );

}